2019-01-24 23:59:39,182 [    INFO] job start
2019-01-24 23:59:39,183 [   ERROR] list index out of range
Traceback (most recent call last):
  File "batch_job.py", line 44, in <module>
    logger.error("arg1 = {0}".format(args[0]))
IndexError: list index out of range
2019-01-24 23:59:48,762 [    INFO] job start
2019-01-24 23:59:48,763 [    INFO] False
2019-01-24 23:59:48,763 [   ERROR] name 'config' is not defined
Traceback (most recent call last):
  File "batch_job.py", line 50, in <module>
    logger.info(config.get("section1","key1"))
NameError: name 'config' is not defined
2019-01-25 00:00:03,641 [    INFO] job start
2019-01-25 00:00:03,641 [    INFO] False
2019-01-25 00:00:03,642 [   ERROR] My Exception
Traceback (most recent call last):
  File "batch_job.py", line 48, in <module>
    raise Exception("My Exception")
Exception: My Exception
2019-01-25 00:01:48,064 [    INFO] job start
2019-01-25 00:01:48,069 [   ERROR] (1146, "Table 'msa_db.Transaction' doesn't exist")
Traceback (most recent call last):
  File "batch_job.py", line 45, in <module>
    cursor.execute("SELECT * FROM Transaction")
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1146, "Table 'msa_db.Transaction' doesn't exist")
2019-01-25 00:03:09,057 [    INFO] job start
2019-01-25 00:03:09,060 [    INFO] False
2019-01-25 00:03:33,984 [    INFO] job start
2019-01-25 00:03:33,985 [    INFO] ()
2019-01-25 00:03:33,986 [    INFO] False
2019-01-25 00:04:09,199 [    INFO] job start
2019-01-25 00:04:09,200 [    INFO] False
2019-01-25 00:06:54,653 [    INFO] job start
2019-01-25 00:06:54,675 [    INFO] False
2019-01-25 00:09:12,755 [    INFO] job start
2019-01-25 00:09:12,758 [   ERROR] (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[ASC]' at line 1")
Traceback (most recent call last):
  File "batch_job.py", line 47, in <module>
    cursor.execute("select * from balance_transaction order by wallet_id [ASC]")
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[ASC]' at line 1")
2019-01-25 00:09:19,350 [    INFO] job start
2019-01-25 00:09:19,352 [   ERROR] (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[ASC]' at line 1")
Traceback (most recent call last):
  File "batch_job.py", line 47, in <module>
    cursor.execute("select * from balance_transaction order by wallet_id[ASC]")
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[ASC]' at line 1")
2019-01-25 00:09:40,562 [    INFO] job start
2019-01-25 00:09:40,564 [   ERROR] (1054, "Unknown column 'wallet_id' in 'order clause'")
Traceback (most recent call last):
  File "batch_job.py", line 47, in <module>
    cursor.execute("select * from balance_transaction order by wallet_id asc")
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1054, "Unknown column 'wallet_id' in 'order clause'")
2019-01-25 00:10:25,586 [    INFO] job start
2019-01-25 00:10:25,604 [    INFO] False
2019-01-25 00:12:05,280 [    INFO] job start
2019-01-25 00:12:05,288 [    INFO] False
2019-01-25 00:16:24,572 [    INFO] job start
2019-01-25 00:16:24,574 [   ERROR] 'dict' object has no attribute 'append'
Traceback (most recent call last):
  File "batch_job.py", line 51, in <module>
    wallet_list.append(wallet)
AttributeError: 'dict' object has no attribute 'append'
2019-01-25 00:16:38,125 [    INFO] job start
2019-01-25 00:16:38,128 [    INFO] False
2019-01-25 00:18:19,138 [    INFO] job start
2019-01-25 00:18:19,139 [   ERROR] 'tuple' object has no attribute 'wallet_id'
Traceback (most recent call last):
  File "batch_job.py", line 51, in <module>
    wallet_list.append(wallet.wallet_id)
AttributeError: 'tuple' object has no attribute 'wallet_id'
2019-01-25 00:22:26,614 [    INFO] job start
2019-01-25 00:22:26,617 [    INFO] False
2019-01-25 00:25:02,263 [    INFO] job start
2019-01-25 00:25:02,270 [   ERROR] I/O operation on closed file.
Traceback (most recent call last):
  File "batch_job.py", line 56, in <module>
    writer.writerows(wallet_list)
ValueError: I/O operation on closed file.
2019-01-25 00:26:09,271 [    INFO] job start
2019-01-25 00:26:09,275 [    INFO] False
2019-01-25 00:26:27,979 [    INFO] job start
2019-01-25 00:26:27,984 [    INFO] False
2019-01-25 00:30:31,573 [    INFO] job start
2019-01-25 00:30:31,577 [    INFO] False
2019-01-25 00:32:50,918 [    INFO] job start
2019-01-25 00:32:50,922 [    INFO] False
2019-01-25 00:35:18,589 [    INFO] job start
2019-01-25 00:35:18,594 [    INFO] False
2019-01-25 00:39:36,429 [    INFO] job start
2019-01-25 00:39:36,434 [   ERROR] 'tuple' object is not callable
Traceback (most recent call last):
  File "batch_job.py", line 72, in <module>
    wallet_id = wallet(0)
TypeError: 'tuple' object is not callable
2019-01-25 00:40:43,910 [    INFO] job start
2019-01-25 00:40:43,915 [   ERROR] 'list' object is not callable
Traceback (most recent call last):
  File "batch_job.py", line 72, in <module>
    wallet_id = wallet(0)
TypeError: 'list' object is not callable
2019-01-25 00:42:04,052 [    INFO] job start
2019-01-25 00:42:04,058 [   ERROR] 'list' object is not callable
Traceback (most recent call last):
  File "batch_job.py", line 73, in <module>
    wallet_id = wallet(0)
TypeError: 'list' object is not callable
2019-01-25 00:44:39,445 [    INFO] job start
2019-01-25 00:44:39,450 [   ERROR] list index out of range
Traceback (most recent call last):
  File "batch_job.py", line 74, in <module>
    transaction_wallet_id = transaction[7]
IndexError: list index out of range
2019-01-25 00:45:03,419 [    INFO] job start
2019-01-25 00:45:03,425 [    INFO] False
2019-01-25 00:46:09,162 [    INFO] job start - program : batch_job
2019-01-25 00:46:09,168 [    INFO] False
2019-01-25 00:46:57,282 [    INFO] job start - program : batch_job
2019-01-25 00:46:57,287 [   ERROR] name 'options' is not defined
Traceback (most recent call last):
  File "batch_job.py", line 75, in <module>
    logger.info(options.debug)
NameError: name 'options' is not defined
2019-01-25 00:51:48,698 [    INFO] job start - program : batch_job
2019-01-25 00:51:48,703 [    INFO] consistency error
2019-01-25 00:51:48,703 [   ERROR] must be str, not int
Traceback (most recent call last):
  File "batch_job.py", line 82, in <module>
    logger.info("wallet_id=" + wallet_id)
TypeError: must be str, not int
2019-01-25 00:52:07,885 [    INFO] job start - program : batch_job
2019-01-25 00:52:07,890 [    INFO] consistency error
2019-01-25 00:52:07,891 [   ERROR] must be str, not int
Traceback (most recent call last):
  File "batch_job.py", line 82, in <module>
    logger.info("wallet_id=" + wallet_id)
TypeError: must be str, not int
2019-01-25 00:52:22,656 [    INFO] job start - program : batch_job
2019-01-25 00:52:22,662 [    INFO] consistency error
2019-01-25 00:52:22,662 [    INFO] wallet_id=1
2019-01-25 00:52:22,662 [    INFO] master_balance=1324601
2019-01-25 00:52:22,663 [    INFO] total_amount=0
2019-01-25 00:52:22,663 [    INFO] consistency error
2019-01-25 00:52:22,663 [    INFO] wallet_id=2
2019-01-25 00:52:22,663 [    INFO] master_balance=19675399
2019-01-25 00:52:22,664 [    INFO] total_amount=0
2019-01-25 00:52:22,664 [    INFO] False
2019-01-25 00:54:00,792 [    INFO] job start - program : batch_job
2019-01-25 00:54:00,810 [    INFO] consistency error
2019-01-25 00:54:00,810 [    INFO] wallet_id=1
2019-01-25 00:54:00,810 [    INFO] master_balance=1324601
2019-01-25 00:54:00,810 [    INFO] total_amount=0
2019-01-25 00:54:00,810 [    INFO] consistency error
2019-01-25 00:54:00,810 [    INFO] wallet_id=2
2019-01-25 00:54:00,810 [    INFO] master_balance=19675399
2019-01-25 00:54:00,810 [    INFO] total_amount=0
2019-01-25 00:54:00,810 [    INFO] False
2019-01-25 01:19:26,645 [    INFO] job start - program : batch_job
2019-01-25 01:19:26,651 [    INFO] False
2019-01-25 01:20:22,915 [    INFO] job start - program : batch_job
2019-01-25 01:20:22,920 [    INFO] False
2019-01-25 01:20:44,921 [    INFO] job start - program : batch_job
2019-01-25 01:20:44,926 [    INFO] False
2019-01-25 01:21:01,907 [    INFO] job start - program : batch_job
2019-01-25 01:21:01,913 [    INFO] False
2019-01-25 01:21:12,911 [    INFO] job start - program : batch_job
2019-01-25 01:21:12,918 [    INFO] False
2019-01-25 01:22:00,262 [    INFO] job start - program : batch_job
2019-01-25 01:22:00,267 [    INFO] False
2019-01-25 01:22:09,216 [    INFO] job start - program : batch_job
2019-01-25 01:22:09,222 [    INFO] False
2019-01-25 01:22:17,023 [    INFO] job start - program : batch_job
2019-01-25 01:22:17,028 [    INFO] False
2019-01-25 01:22:58,899 [    INFO] job start - program : batch_job
2019-01-25 01:22:58,905 [   ERROR] unsupported operand type(s) for +: 'int' and 'list'
Traceback (most recent call last):
  File "batch_job.py", line 83, in <module>
    total_amount = total_amount + transaction_list[2]
TypeError: unsupported operand type(s) for +: 'int' and 'list'
2019-01-25 01:23:31,140 [    INFO] job start - program : batch_job
2019-01-25 01:24:01,513 [    INFO] job start - program : batch_job
2019-01-25 01:24:53,599 [    INFO] job start - program : batch_job
2019-01-25 01:24:53,604 [   ERROR] unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "batch_job.py", line 81, in <module>
    print(wallet_index + ':' + transaction_index)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
2019-01-25 01:25:26,485 [    INFO] job start - program : batch_job
2019-01-25 01:26:54,578 [    INFO] job start - program : batch_job
2019-01-25 01:26:54,597 [    INFO] consistency error
2019-01-25 01:26:54,597 [    INFO] wallet_id=1
2019-01-25 01:26:54,598 [    INFO] master_balance=1324601
2019-01-25 01:26:54,598 [    INFO] total_amount=-19373199
2019-01-25 01:26:54,604 [   ERROR] list index out of range
Traceback (most recent call last):
  File "batch_job.py", line 85, in <module>
    transaction = transaction_list[transaction_index]
IndexError: list index out of range
2019-01-25 01:28:33,719 [    INFO] job start - program : batch_job
2019-01-25 01:28:33,737 [    INFO] consistency error
2019-01-25 01:28:33,738 [    INFO] wallet_id=1
2019-01-25 01:28:33,738 [    INFO] master_balance=1324601
2019-01-25 01:28:33,739 [    INFO] total_amount=-19373199
2019-01-25 01:28:33,745 [   ERROR] list index out of range
Traceback (most recent call last):
  File "batch_job.py", line 84, in <module>
    transaction = transaction_list[transaction_index]
IndexError: list index out of range
2019-01-25 01:30:38,006 [    INFO] job start - program : batch_job
2019-01-25 01:30:38,025 [    INFO] consistency error
2019-01-25 01:30:38,025 [    INFO] wallet_id=1
2019-01-25 01:30:38,026 [    INFO] master_balance=1324601
2019-01-25 01:30:38,026 [    INFO] total_amount=-19373199
2019-01-25 01:30:38,031 [    INFO] False
2019-01-25 01:45:46,386 [    INFO] job start - program : batch_job
2019-01-25 01:45:46,404 [   ERROR] consistency error
2019-01-25 01:45:46,404 [   ERROR] wallet_id=1
2019-01-25 01:45:46,404 [   ERROR] master_balance=1324601
2019-01-25 01:45:46,405 [   ERROR] total_amount=-19373199
2019-01-25 01:45:46,413 [   ERROR] consistency error
2019-01-25 01:45:46,413 [   ERROR] wallet_id=2
2019-01-25 01:45:46,413 [   ERROR] master_balance=19675399
2019-01-25 01:45:46,413 [   ERROR] total_amount=19373199
2019-01-25 01:45:46,413 [    INFO] False
2019-01-25 01:46:34,827 [    INFO] job start - program : batch_job
2019-01-25 01:46:34,832 [   ERROR] consistency error
2019-01-25 01:46:34,833 [   ERROR] wallet_id=1
2019-01-25 01:46:34,833 [   ERROR] master_balance=1324601
2019-01-25 01:46:34,833 [   ERROR] total_amount=-19373199
2019-01-25 01:46:34,834 [   ERROR] consistency error
2019-01-25 01:46:34,834 [   ERROR] wallet_id=2
2019-01-25 01:46:34,834 [   ERROR] master_balance=19675399
2019-01-25 01:46:34,835 [   ERROR] total_amount=19373199
2019-01-25 01:46:34,835 [    INFO] job end - program : batch_job
2019-01-25 01:53:26,509 [    INFO] job start - program : batch_job
2019-01-25 01:53:26,512 [   ERROR] consistency error
2019-01-25 01:53:26,513 [   ERROR] wallet_id=1
2019-01-25 01:53:26,513 [   ERROR] master_balance=501000
2019-01-25 01:53:26,513 [   ERROR] total_amount=1000
2019-01-25 01:53:26,514 [   ERROR] consistency error
2019-01-25 01:53:26,514 [   ERROR] wallet_id=2
2019-01-25 01:53:26,514 [   ERROR] master_balance=499000
2019-01-25 01:53:26,515 [   ERROR] total_amount=-1000
2019-01-25 01:53:26,515 [    INFO] job end - program : batch_job
2019-01-25 01:56:40,031 [    INFO] job start - program : batch_job
2019-01-25 01:56:40,034 [    INFO] consistency success
2019-01-25 01:56:40,034 [    INFO] wallet_id=1
2019-01-25 01:56:40,035 [    INFO] master_balance=500000
2019-01-25 01:56:40,035 [    INFO] total_amount=500000
2019-01-25 01:56:40,035 [    INFO] consistency success
2019-01-25 01:56:40,036 [    INFO] wallet_id=2
2019-01-25 01:56:40,036 [    INFO] master_balance=500000
2019-01-25 01:56:40,036 [    INFO] total_amount=500000
2019-01-25 01:56:40,036 [   ERROR] consistency error
2019-01-25 01:56:40,037 [   ERROR] wallet_id=3
2019-01-25 01:56:40,037 [   ERROR] master_balance=999000000
2019-01-25 01:56:40,037 [   ERROR] total_amount=-1000000
2019-01-25 01:56:40,038 [    INFO] job end - program : batch_job
2019-01-25 01:57:45,092 [    INFO] job start - program : batch_job
2019-01-25 01:57:45,096 [    INFO] consistency success
2019-01-25 01:57:45,096 [    INFO] wallet_id=1
2019-01-25 01:57:45,096 [    INFO] master_balance=497500
2019-01-25 01:57:45,097 [    INFO] total_amount=497500
2019-01-25 01:57:45,097 [    INFO] consistency success
2019-01-25 01:57:45,097 [    INFO] wallet_id=2
2019-01-25 01:57:45,098 [    INFO] master_balance=502500
2019-01-25 01:57:45,098 [    INFO] total_amount=502500
2019-01-25 01:57:45,098 [   ERROR] consistency error
2019-01-25 01:57:45,099 [   ERROR] wallet_id=3
2019-01-25 01:57:45,099 [   ERROR] master_balance=999000000
2019-01-25 01:57:45,099 [   ERROR] total_amount=-1000000
2019-01-25 01:57:45,099 [    INFO] job end - program : batch_job
2019-01-25 01:59:53,037 [    INFO] job start - program : batch_job
2019-01-25 01:59:53,041 [    INFO] consistency success
2019-01-25 01:59:53,041 [    INFO] wallet_id=1
2019-01-25 01:59:53,041 [    INFO] master_balance=497500
2019-01-25 01:59:53,042 [    INFO] total_amount=497500
2019-01-25 01:59:53,042 [    INFO] consistency success
2019-01-25 01:59:53,042 [    INFO] wallet_id=2
2019-01-25 01:59:53,042 [    INFO] master_balance=502500
2019-01-25 01:59:53,043 [    INFO] total_amount=502500
2019-01-25 01:59:53,043 [    INFO] job end - program : batch_job
